apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: application01
    run: html-test
  name: html-test-svc
  namespace: application01
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/instance: application01
    run: html-test
  type: NodePort
status:
  loadBalancer: {}
